name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present

      - name: Compress Build Output
        run: |
          powershell Compress-Archive -Path ./dist/win-unpacked/* -DestinationPath ./dist/duplicate-finder-${{ github.ref_name }}.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/win-unpacked
          asset_name: duplicate-finder-${{ github.ref_name }}.zip
          asset_content_type: application/zip
